(load-option 'format)

(define (test test-name expected-value-source expected-value given-value test predicate)
  (define (report rubric value)
    (format #t "~A: ~A~%" rubric value))
  (report 'test-name test-name)
  (report 'expected-value-source expected-value-source)
  (report 'expected-value expected-value)
  (report 'given-value given-value)
  (report 'test test)
  (report 'result (predicate expected-value given-value)))
