(define (let*->nested-lets exp)
  (let ((bindings (let*-bindings exp))
        (body (let*-body exp)))
    (let descend ((bindings bindings))
      (if (null? (cdr bindings))
          (append (list 'let (list (car bindings))) body)
          (make-let (list (car bindings)) (descend (cdr bindings)))))))
