(load "make-wire.scm")
(load "half-adder.scm")
(load "or-gate.scm")

(define (full-adder a b c-in sum c-out)
  (let ((s (make-wire))
        (c1 (make-wire))
        (c2 (make-wire)))
    (half-adder b c-in c c1)
    (half-adder a s sum c2)
    (or-gate c1 c2 c-out)
    'ok))
