(load "get-signal.scm")
(load "logical-not.scm")
(load "after-delay.scm")
(load "inverter-delay.scm")
(load "set-signal!.scm")
(load "add-action!.scm")

(define (inverter input output)
  (define (invert-input)
    (let ((new-value (logical-not (get-signal input))))
      (after-delay inverter-delay
                   (lambda ()
                     (set-signal! output new-value)))))
  (add-action! input invert-input)
  'ok)
