#!/usr/bin/env chicken-scheme
(use debug sicp-eval sicp-eval-amb test)

(with-require `((< ,<)
                (+ ,+)
                (= ,=)
                (* ,*)
                (list ,list))
  (lambda (env)
    (ambeval* '(define (an-integer-between low high)
                 (require (< low high))
                 (amb low (an-integer-between (+ low 1) high)))
              env)
    (ambeval* '(define (a-pythagorean-triple-starting-from low)
                 (let ((i (an-integer-starting-from low)))
                   (let ((j (an-integer-between low (+ i 1))))
                     (let ((k (an-integer-between low (+ j 1))))
                       (require (= (+ (* k k) (* j j)) (* i i)))
                       (list k j i)))))
              env)
    (test "First ten pythagorean triples"
          '((3 4 5)
            (6 8 10)
            (5 12 13)
            (9 12 15)
            (8 15 17)
            (12 16 20)
            (15 20 25)
            (7 24 25)
            (10 24 26)
            (20 21 29))
          (ambeval* '(a-pythagorean-triple-starting-from 1) env 10))))
