(define (adjoin-position new-row k rest-of-queens)
;;   (display new-row)
;;   (display k)
;;   (display rest-of-queens)
;;   (display (cons new-row rest-of-queens))
;;   (newline)
  (cons new-row rest-of-queens))
