(define (run-battery battery evaluator)
  (for-each (lambda (test)
              (test (lambda (evaluanda testandum)
                      (let ((result (testandum (evaluator evaluanda))))
                        (format #t "value: ~A~%~%" result)))))
            battery))
