(load "make-rectangle-diagonal.scm")
(load "width-rectangle-diagonal.scm")
(load "length-rectangle-diagonal.scm")
(load "print-rectangle-diagonal.scm")
(load "d1-rectangle-diagonal.scm")
(load "d2-rectangle-diagonal.scm")
