(load "no-operands?.scm")
(load "actual-value.scm")
(load "rest-operands.scm")
(load "first-operand.scm")

(define (list-of-arg-values exps env)
  (if (no-operands? exps)
      '()
      (cons (actual-value (first-operand exps) env)
            (list-of-arg-values (rest-operands exps)
                                env))))
