;;; Solutions copyright (C) 2007, Peter Danenberg; http://wizardbook.org
;;; Source code copyright (C) 1996, MIT; http://mitpress.mit.edu/sicp

(load "install-scheme-number-package.scm")
(load "install-complex-package.scm")
(load "install-rational-package.scm")
(load "equ?.scm")
(load "make-complex-from-mag-ang.scm")
(load "make-complex-from-real-imag.scm")
(load "make-rational.scm")
(load "make-scheme-number.scm")

(install-scheme-number-package)
(install-complex-package)
(install-rational-package)

(define polar1 (make-complex-from-mag-ang 1 45))
(define polar2 (make-complex-from-mag-ang 1 45))
(define polar3 (make-complex-from-mag-ang 2 90))
(define rectangular1 (make-complex-from-real-imag 1 1))
(define rectangular2 (make-complex-from-real-imag 1 1))
(define rectangular3 (make-complex-from-real-imag 2 2))
(define rational1 (make-rational 1 2))
(define rational2 (make-rational 1 2))
(define rational3 (make-rational 3 4))
(define scheme1 (make-scheme-number 1))
(define scheme2 (make-scheme-number 1))
(define scheme3 (make-scheme-number 2))

(equ? polar1 polar2)
(equ? polar1 polar3)
(equ? rectangular1 rectangular2)
(equ? rectangular1 rectangular3)
(equ? rational1 rational2)
(equ? rational1 rational3)
(equ? scheme1 scheme2)
(equ? scheme1 scheme3)
