(load "add-streams.scm")
(load "display-stream-n.scm")

;;     1 ...
;;     1 ...
;;   1 1 ...
;; 1 1 1 ...
;; ---------
;; 1 2 4 8 ...

(define s (cons-stream 1 (add-streams s s)))
(display-stream-n s 10)
