(define (make-restore inst machine stack pc)
  (let ((name (stack-inst-reg-name inst)))
    (let ((reg (get-register machine name)))
      (lambda ()
        ((machine 'add-saved/restored-reg!) name)
        (set-contents! reg (pop stack))    
        (advance-pc pc)))))
