(load "install-application-package.scm")
(load "install-assignment-package.scm")
(load "install-begin-package.scm")
(load "install-cond-package.scm")
(load "install-definition-package.scm")
(load "install-if-package.scm")
(load "install-lambda-package.scm")
(load "install-quoted-package.scm")
(load "install-self-evaluating-package.scm")
(load "install-variable-package.scm")

(define (install-packages)
  (install-application-package)
  (install-assignment-package)
  (install-begin-package)
  (install-cond-package)
  (install-definition-package)
  (install-if-package)
  (install-lambda-package)
  (install-quoted-package)
  (install-self-evaluating-package)
  (install-variable-package))
