(load "entry-tree.scm")
(load "left-branch-tree.scm")
(load "right-branch-tree.scm")

(define (element-of-set? x set)
  (cond ((null? set) false)
        ((= x (entry set)) true)
        ((< x (entry set))
         (element-of-set? x (left-branch set)))
        ((> x (entry set))
         (element-of-set? x (right-branch set)))))
