(load "put.scm")
(load "attach-tag.scm")
(load "make-rational.scm")
(load "tag-rational.scm")
(load "scheme-number?.scm")
(load "add.scm")
(load "sub.scm")
(load "mul.scm")
(load "div.scm")
(load "equ?.scm")
(load "put-irreducible.scm")
(load "negate.scm")
(load "=zero?.scm")
(load "reduce.scm")

(define (install-rational-package)
  (define (numer x) (car x))
  (define (denom x) (cadr x))
  ;;   (define (make-rat n d)
  ;;     (let ((g (gcd n d)))
  ;;       (cons (/ n g) (/ d g))))
  (define (make-rat n d)
    ;;(cons n d)
    (reduce n d)
    )
  (define (add-rat x y)
    (make-rat (add (mul (numer x) (denom y))
                   (mul (numer y) (denom x)))
              (mul (denom x) (denom y))))
  (define (sub-rat x y)
    (make-rat (sub (mul (numer x) (denom y))
                   (mul (numer y) (denom x)))
              (mul (denom x) (denom y))))
  (define (mul-rat x y)
    (make-rat (mul (numer x) (numer y))
              (mul (denom x) (denom y))))
  (define (div-rat x y)
    (make-rat (mul (numer x) (denom y))
              (mul (denom x) (numer y))))
  (define (equ-rat? x y)
    (and (equ? (numer x) (numer y))
         (equ? (denom x) (denom y))))
  (define (cosine r)
    (cos (rational->real r)))
  (define (sine r)
    (sine (rational->real r)))
  (define (atangent r)
    (atan (rational->real r)))
  (define (square r)
    (mul-rat r r))
  (define (square-root r)
    (sqrt (rational->real r)))

  (define (tag x) (tag-rational x))
  (put 'add '(rational rational)
       (lambda (x y) (tag (add-rat x y))))
  (put 'sub '(rational rational)
       (lambda (x y) (tag (sub-rat x y))))
  (put 'mul '(rational rational)
       (lambda (x y) (tag (mul-rat x y))))
  (put 'div '(rational rational)
       (lambda (x y) (tag (div-rat x y))))
  (put 'equ? '(rational rational)
       (lambda (x y) (equ-rat? x y)))
  (put '=zero? '(rational)
       (lambda (x) (=zero? (numer x))))
  (put 'numer '(rational) numer)
  (put 'denom '(rational) denom)
  (put 'cosine '(rational) cosine)
  (put 'sine '(rational) sine)
  (put 'atangent '(rational) atangent)
  (put 'square '(rational) square)
  (put 'square-root '(rational) square-root)
  (put 'negate '(rational)
       (lambda (x) (make-rat (negate (numer x)) (denom x))))

  (put 'make 'rational
       (lambda (n d) (tag (make-rat n d))))

  ;; Coercion
  (define (rational->real r)
    (let* ((numerator (numer r))
           (denominator (denom r)))
      (div numerator denominator)))

  ;; Scheme-number: placeholder for int
;;   (define (rational->scheme-number r)
;;     (put-irreducible 'rational->scheme-number)
;;     (let ((ratio (rational->real r)))
;;       (if (scheme-number? ratio)
;;           (round ratio)
;;           ratio)))
;;   (put 'project '(rational) rational->scheme-number)

  (define (scheme-number->rational n)
    (make-rational n 1))
  (put-coercion 'scheme-number 'rational scheme-number->rational)
  (put 'raise '(scheme-number)
       (lambda (n) (scheme-number->rational n)))

  'done)
