(load "register-machine-context.scm")
(load "syntax-context.scm")
(load "evaluator-context.scm")

;; (load "register-machine/make-new-machine-stacks.scm")
;; (load "register-machine/make-restore-stacks.scm")
;; (load "register-machine/make-save-stacks.scm")

(load "eceval-lazy/actual-value.scm")
(load "eceval-lazy/apply-dispatch.scm")
(load "eceval-lazy/compound-apply.scm")
(load "eceval-lazy/delay-it.scm")
(load "eceval-lazy/done.scm")
(load "eceval-lazy/eceval-global.scm")
(load "eceval-lazy/eceval-operations.scm")
(load "eceval-lazy/eval-dispatch.scm")
(load "eceval-lazy/eval.scm")
(load "eceval-lazy/ev-and.scm")
(load "eceval-lazy/ev-appl-accum-last-arg.scm")
(load "eceval-lazy/ev-appl-accum-last-arg-value.scm")
(load "eceval-lazy/ev-appl-accum-last-delayed-arg.scm")
(load "eceval-lazy/ev-appl-accumulate-arg.scm")
(load "eceval-lazy/ev-appl-accumulate-arg-value.scm")
(load "eceval-lazy/ev-appl-accumulate-delayed-arg.scm")
(load "eceval-lazy/ev-appl-delayed-operand-loop.scm")
(load "eceval-lazy/ev-appl-did-operator.scm")
(load "eceval-lazy/ev-application.scm")
(load "eceval-lazy/ev-appl-last-arg.scm")
(load "eceval-lazy/ev-appl-last-arg-value.scm")
(load "eceval-lazy/ev-appl-last-delayed-arg.scm")
(load "eceval-lazy/ev-appl-operand-loop.scm")
(load "eceval-lazy/ev-appl-operand-value-loop.scm")
(load "eceval-lazy/ev-assignment-1.scm")
(load "eceval-lazy/ev-assignment.scm")
(load "eceval-lazy/ev-begin.scm")
(load "eceval-lazy/ev-cond.scm")
(load "eceval-lazy/ev-definition-1.scm")
(load "eceval-lazy/ev-definition.scm")
(load "eceval-lazy/ev-if-alternative.scm")
(load "eceval-lazy/ev-if-consequent.scm")
(load "eceval-lazy/ev-if-decide.scm")
(load "eceval-lazy/ev-if.scm")
(load "eceval-lazy/ev-lambda.scm")
(load "eceval-lazy/ev-let.scm")
(load "eceval-lazy/ev-let*.scm")
(load "eceval-lazy/ev-or.scm")
(load "eceval-lazy/ev-quoted.scm")
(load "eceval-lazy/ev-self-eval.scm")
(load "eceval-lazy/ev-sequence-continue.scm")
(load "eceval-lazy/ev-sequence-last-exp.scm")
(load "eceval-lazy/ev-sequence.scm")
(load "eceval-lazy/ev-variable.scm")
(load "eceval-lazy/force-it.scm")
(load "eceval-lazy/force-it-thunk.scm")
(load "eceval-lazy/perform-error.scm")
(load "eceval-lazy/primitive-apply.scm")
(load "eceval-lazy/print-result.scm")
(load "eceval-lazy/read-eval-print-loop.scm")
(load "eceval-lazy/signal-error.scm")
(load "eceval-lazy/unknown-expression-type.scm")
(load "eceval-lazy/unknown-procedure-type.scm")

(load "eceval-lazy/eceval.scm")
'done
