(load-option 'format)
(load "evaluator-tests/and-test.scm")
(load "evaluator-tests/application-test.scm")
(load "evaluator-tests/assignment-test.scm")
(load "evaluator-tests/cond-test.scm")
(load "evaluator-tests/definition-test.scm")
(load "evaluator-tests/extended-cond-test.scm")
(load "evaluator-tests/if-test.scm")
(load "evaluator-tests/let-test.scm")
(load "evaluator-tests/make-test.scm")
(load "evaluator-tests/named-let-test.scm")
(load "evaluator-tests/or-test.scm")
(load "evaluator-tests/run-battery.scm")
(load "evaluator-tests/self-evaluating-test.scm")
(load "evaluator-tests/test-battery.scm")
'done
