(load "add-rat.scm")
(load "sub-rat.scm")
(load "mul-rat.scm")
(load "div-rat.scm")
(load "equal-rat.scm")
(load "make-rat.scm")
(load "print-rat.scm")
(load "numer.scm")
(load "denom.scm")

;; (define one-half (make-rat 1 2))
;; (define one-third (make-rat 1 3))
;; (print-rat one-half)
;; (print-rat one-third)
;; (print-rat (add-rat one-half one-third))
;; (print-rat (mul-rat one-half one-third))
;; (print-rat (add-rat one-third one-third))
