(define (install-require-package)
  (define (require-predicate exp) (cadr exp))
  (define (analyze-require exp)
    (let ((pproc (analyze (require-predicate exp))))
      (lambda (env succeed fail)
        (pproc env
               (lambda (pred-value fail2)
                 (if (not pred-value)
                     (fail2)
                     (succeed 'ok fail2)))
               fail))))
  (put-amb 'require analyze-require)
  'done)
